repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: ^fouine/
        types: [file, python]
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          "--color=amways",
          "--count",
          "--statistics",
          "--max-line-length=88",
          "--extend-ignore=E203,E266,F401,F403,F405,E501,F524,F601,W605,E722,F722,F811,F821,F841",
          "extend-exclude=*.py[cod]"
          ]
