repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        files: ^src/
        types: [file, python]
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

  - repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        entry: flakeheaven lint
        language: system
        files: ^src/
        types: [file, python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        files: ^src/
        types: [file, python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: ^src/
        types: [file, python]
