site_name: Fouine
site_description: "The documentation of Fouine forensic tool."

repo_name: Github
repo_url: https://github.com/You-ne/2600_Forensic_Tool

docs_dir: docs/
theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/

nav:
  - Home: index.md
  - Installation: Installation.md
  - Tutorial: "Basic Usage.md"
  - About Targets: "About Targets.md"
  - About this Documentation: "About this documentation.md"
  - License: "License.md"
  - API Documentation:
      - src/:
        - fouine: "src/fouine/fouine.md"
        - .core:
            - ._defcfg: "src/fouine/core/_defcfg.md"
            - ._helper: "src/fouine/core/_helper.md"
            - .parsing: "src/fouine/core/parsing.md"
            - .core: "src/fouine/core/core.md"
            - .logs: "src/fouine/core/logs.md"


