[tool.poetry]
name = "fouine"
version = "0.1.0"
description = ""
authors = ["you"]
license = "MIT"
readme = "README.md"

###

[tool.poetry.dependencies]
python = "^3.10"

###

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]

###
black = "^23.1.0"
flake8 = "^6.0.0"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]

###
sphinx = "^6.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
