Description: User Related Registry hives
Author: Eric Zimmerman / Mark Hallman
Version: 1.0
Id: 635fbfd3-4a47-45b5-aae4-0a1bb6545d08
RecreateDirectories: true
Targets:
    -
        Name: NTUSER.DAT registry hive XP
        Category: Registry
        Path: C:\Documents and Settings\%user%\
        FileMask: NTUSER.DAT
    -
        Name: NTUSER.DAT registry hive
        Category: Registry
        Path: C:\Users\%user%\
        FileMask: NTUSER.DAT
    -
        Name: NTUSER.DAT registry transaction files
        Category: Registry
        Path: C:\Users\%user%\
        FileMask: NTUSER.DAT.LOG*
    -
        Name: NTUSER.DAT DEFAULT registry hive
        Category: Registry
        Path: C:\Windows\System32\config\
        FileMask: DEFAULT
    -
        Name: NTUSER.DAT DEFAULT registry hive
        Category: Registry
        Path: C:\Windows.old\Windows\System32\config\
        FileMask: DEFAULT
    -
        Name: NTUSER.DAT DEFAULT transaction files
        Category: Registry
        Path: C:\Windows\System32\config\
        FileMask: DEFAULT.LOG*
    -
        Name: NTUSER.DAT DEFAULT transaction files
        Category: Registry
        Path: C:\Windows.old\Windows\System32\config\
        FileMask: DEFAULT.LOG*
    -
        Name: UsrClass.dat registry hive
        Category: Registry
        Path: C:\Users\%user%\AppData\Local\Microsoft\Windows\
        FileMask: UsrClass.dat
    -
        Name: UsrClass.dat registry transaction files
        Category: Registry
        Path: C:\Users\%user%\AppData\Local\Microsoft\Windows\
        FileMask: UsrClass.dat.LOG*
